# Generated by Django 2.0.5 on 2018-05-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cspreport',
            name='blocked_uri',
            field=models.URLField(help_text='URI of the resource that was prevented from loading due to the policy violation, with any fragment component removed', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cspreport',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True, help_text='When this report was received'),
        ),
        migrations.AlterField(
            model_name='cspreport',
            name='document_uri',
            field=models.URLField(help_text='The address of the protected resource, with any fragment component removed', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cspreport',
            name='original_policy',
            field=models.TextField(help_text='The original policy as received by the user-agent.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cspreport',
            name='referrer',
            field=models.URLField(help_text='The referrer attribute of the protected resource', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cspreport',
            name='sender_ip',
            field=models.GenericIPAddressField(help_text='IP of the browser sending this report'),
        ),
        migrations.AlterField(
            model_name='cspreport',
            name='user_agent',
            field=models.CharField(help_text='User-Agent of reporting browser', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cspreport',
            name='violated_directive',
            field=models.CharField(help_text='The policy directive that was violated', max_length=1000),
        ),
        migrations.AlterField(
            model_name='passwordexpiry',
            name='password_expiry_date',
            field=models.DateTimeField(auto_now_add=True, help_text="The date and time when the user's password expires. If this is empty, the password never expires.", null=True),
        ),
    ]
